-- AUTO-GENERATED by scripts/gen-seed-sql.mjs — run in the Supabase SQL editor.
-- Idempotent: re-running skips rows that already exist (on conflict do nothing).
begin;

-- local_committees (3)
insert into local_committees ("id", "name", "country", "lcpId", "lcvpIds") values ('lc_ghent', 'LC Ghent', 'Belgium', 'usr_pavlos', '{"usr_tijs"}') on conflict (id) do nothing;
insert into local_committees ("id", "name", "country", "lcpId", "lcvpIds") values ('lc_antwerp', 'LC Antwerp', 'Belgium', 'usr_roxy', '{"usr_adam"}') on conflict (id) do nothing;
insert into local_committees ("id", "name", "country", "lcpId", "lcvpIds") values ('lc_leuven', 'LC Leuven', 'Belgium', 'usr_alandra', '{"usr_felix"}') on conflict (id) do nothing;

-- users (22)
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_admin', 'Aboulkacem (MCVP iGT)', 'admin@aib.org', 'admin', NULL, 'MCVP Sales', NULL, true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_adam', 'Adam', 'adam@aiesec.be', 'lcvp', 'lc_antwerp', 'VP Sales', NULL, true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_alandra', 'Alandra', 'alandra@aiesec.be', 'lcp', 'lc_leuven', 'Local Committee President', NULL, true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_carmela', 'Carmela', 'carmela@aiesec.be', 'member', 'lc_ghent', 'Sales Member', 'usr_tijs', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_daksh', 'Daksh', 'daksh@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_delia', 'Delia', 'delia@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_dieter', 'Dieter', 'dieter@aiesec.be', 'member', 'lc_antwerp', 'Sales Member', 'usr_adam', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_ebrahim', 'Ebrahim', 'ebrahim@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_felix', 'Felix', 'felix@aiesec.be', 'lcvp', 'lc_leuven', 'VP Sales', NULL, true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_jeremy', 'Jeremy', 'jeremy@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_kobe', 'Kobe', 'kobe@aiesec.be', 'member', 'lc_ghent', 'Sales Member', 'usr_tijs', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_linda', 'Linda', 'linda@aiesec.be', 'member', 'lc_ghent', 'Sales Member', 'usr_tijs', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_mariia', 'Mariia', 'mariia@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_marit', 'Marit', 'marit@aiesec.be', 'member', 'lc_antwerp', 'Sales Member', 'usr_adam', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_nazar', 'Nazar', 'nazar@aiesec.be', 'member', 'lc_antwerp', 'Sales Member', 'usr_adam', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_nico', 'Nico', 'nico@aiesec.be', 'member', 'lc_antwerp', 'Sales Member', 'usr_adam', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_pavlos', 'Pavlos', 'pavlos@aiesec.be', 'lcp', 'lc_ghent', 'Local Committee President', NULL, true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_pratyksshi', 'Pratyksshi', 'pratyksshi@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_rayhan', 'Rayhan', 'rayhan@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_roxy', 'Roxy', 'roxy@aiesec.be', 'lcp', 'lc_antwerp', 'Local Committee President', NULL, true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_tijs', 'Tijs', 'tijs@aiesec.be', 'lcvp', 'lc_ghent', 'VP Sales', NULL, true) on conflict (id) do nothing;
insert into users ("id", "name", "email", "role", "lcId", "position", "teamLeadId", "active") values ('usr_yodi', 'Yodi', 'yodi@aiesec.be', 'member', 'lc_leuven', 'Sales Member', 'usr_felix', true) on conflict (id) do nothing;

commit;
